### ISSUE TITLE
energy values are wrong

### ISSUE THREAD

**Issue by vikt0rm** [fabian-lauer/dbus-shelly-3em-smartmeter#2]
Hi Fabian,

i was not able to create a branch to fix it on my own. Here the fix:

Changing to value from "power" to "total" for Forward like:  
`self._dbusservice['/Ac/L1/Energy/Forward'] = meter_data['emeters'][0]['total']/1000 if meter_data['emeters'][0]['total'] > 0 else 0`
Changing to value from "power" to "total_returned" for Reverse like:  
`self._dbusservice['/Ac/L1/Energy/Reverse'] = (meter_data['emeters'][0]['total_returned']/1000) if meter_data['emeters'][0]['total_returned'] < 0 else 0`

This change works on my setup like expected.

BR,
Viktor

**Comment by fabian-lauer** [comment]
Hi,

Thanks for info.
I was looking a round for a couple of days to find my error - found it this morning🙈

Fix is almost the same….thanks for your help …. A few days early would have been even better 😁

Will push changes during the next hours

Cheers
Fabian

—-
Fabian Lauer
Mobil: +49 170/2761382
________________________________
Von: vikt0rm ***@***.***>
Gesendet: Monday, March 28, 2022 11:19:08 AM
An: fabian-lauer/dbus-shelly-3em-smartmeter ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [fabian-lauer/dbus-shelly-3em-smartmeter] energy values are wrong (Issue #2)


Hi Fabian,

i was not able to create a branch to fix it on my own. Here the fix:

Changing to value from "power" to "total" for Forward like:
self._dbusservice['/Ac/L1/Energy/Forward'] = meter_data['emeters'][0]['total']/1000 if meter_data['emeters'][0]['total'] > 0 else 0
Changing to value from "power" to "total_returned" for Reverse like:
self._dbusservice['/Ac/L1/Energy/Reverse'] = (meter_data['emeters'][0]['total_returned']/1000) if meter_data['emeters'][0]['total_returned'] < 0 else 0`

This change works on my setup like expected.

BR,
Viktor

**Comment by fabian-lauer** [comment]
Problem has been fixed - new release v0.2 is out

**Comment by vikt0rm** [comment]
Sorry I installed Venus OS on my raspi just the day before yesterday :) but I was able to make fast progress 👍 Thank you for your inspiration!
