### ISSUE TITLE
Can this be transformed for Shelly EM - monophase?

### ISSUE THREAD

**Issue by xenonshop** [fabian-lauer/dbus-shelly-3em-smartmeter#24]
Hi!
Hope you have time to change the script for a Shelly EM.
Here is the output for it:
{"power":2724.16,"reactive":-1050.38,"pf":-0.93,"voltage":221.42,"is_valid":true,"total":12716863.2,"total_returned":1742722.0}

**Comment by Brekkis** [comment]
https://github.com/vincegod/dbus-shelly-em-smartmeter
