### ISSUE TITLE
Not running as service at v2.93 large after shutdown / reboot

### ISSUE THREAD

**Issue by dafricki** [fabian-lauer/dbus-shelly-3em-smartmeter#32]
It seems when using the Venus OS Large Image v2.93 there is a problem with the service when the Raspberry was shutted down and then started a few hours later. 
Then there are no values from the dbus-shelly-3em-smartmeter at "AC-Eingang" and "AC-Lasten" and dbus-spy shows no 3EM service.

**Comment by fabian-lauer** [comment]
Hi @dafricki ,

looks like this is a linked issue - see https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter/issues/33 
Not using large image nor raspberry.
Therefore I can't test :-(

**Comment by andreasnanko** [comment]
Thats because the install script is broken due to wrong quotes. 
You need to change it to double quotes instead of single.

```grep -qxF '$SCRIPT_DIR/install.sh' $filename || echo '$SCRIPT_DIR/install.sh' >> $filename```

will result into 

```$SCRIPT_DIR/install.sh```

where you wanted to inject the script path

So you want to change it to 

```grep -qxF "$SCRIPT_DIR/install.sh" $filename || echo "$SCRIPT_DIR/install.sh" >> $filename```

**Comment by andreasnanko** [comment]
You don't need to run special commands, you need to fix the install.sh file. Afterwards just as described in the install documentation.

**Comment by dafricki** [comment]
Thank you very much, now it seems to work.

**Comment by fabian-lauer** [comment]
Updated in main-branch
