### ISSUE TITLE
there is a problem with the service when the raspberry reboot

### ISSUE THREAD

**Issue by laserinho** [fabian-lauer/dbus-shelly-3em-smartmeter#33]
there is a problem with the service when the raspberry reboot
Then there are no values ​​from the dbus-shelly-3em-smartmeter at "AC input" and device list shows no 3EM service.

**Comment by fabian-lauer** [comment]
Hi @laserinho,

thanks for input - will doublecheck.
The problem I have: not running on raspberry at all. just GX device.
So when solution is working on raspberry its fine for me - if not, it is like it is.

If you can provide me details about error or even better how-to fix I will be happy to add...

**Comment by ThomasLohner** [comment]
@laserinho This was a bug in install script, it was fixed in #32

**Comment by laserinho** [comment]
now it's working
Thanks a lot
