### ISSUE TITLE
support for 1EM

### ISSUE THREAD

**Issue by ramack** [fabian-lauer/dbus-shelly-3em-smartmeter#37]
What do you think about adding support for the 1EM shelly?

(I have a micro-inverter on the AC out on my Multiplus 2, connected via an 1EM shelly, and it would be quite cool to integrate it into my Venus stuff. - It looks straight forward to do it in a separate project, but maybe you would be interested in supporting both the 1 and the 3 channel shelly)

**Comment by fabian-lauer** [comment]
Hey @ramack ,

please have a look in the discussions: https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter/discussions/10
There are a few interesting things available.

Will close this topic/issue here as it is not shelly-3em related.

Fabian

**Comment by ramack** [comment]
Thanks. I even have a 1PM not a 1EM :grin: but I found https://github.com/vikt0rm/dbus-shelly-1pm-pvinverter

But somehow it would great, if all those shelly devices would be supported in on VenusOS driver, @fabian-lauer @vikt0rm @vincegod what do you think about that?

**Comment by fabian-lauer** [comment]
Oh my fault @ramack  -  your idea is good, but we would need a better concept in this case and at least for me a bit more of time on such a project :-/
