### ISSUE TITLE
IP V6

### ISSUE THREAD

**Issue by qwert4712** [fabian-lauer/dbus-shelly-3em-smartmeter#46]
Hi Fabian,

thanks a lot for the script.
On my Raspi with Venus OS it's working fine.

My cousin has a Gerbo connected to a fritzbox.
in this case the Gerbo has an IP V4 and an IP V6 Address!

From a SSH Terminal  on the Gerbo  the Shelly with the IP v4 address is not reachable by ping (also not with your script)

The shelly seems not to able to deal with a IP v6

Do you know if I can disable IP v6 on the Gerbo?
Or any other idea?

Thx 
Michael

**Comment by fabian-lauer** [comment]
Hi @qwert4712 ,

sorry can't help here as I don't use IPv6 in my private network at all - maybe a tip (not sure if working) is to setup IP manually in web-interface like here:
![image](https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter/assets/101807694/234e1ca7-8502-458b-b900-8aed59224edb)

I also disabled WIFI at all, as connected via Ethernet.

For more assistance I would always recommend the Victron community: https://community.victronenergy.com/index.html

Fabian

**Comment by qwert4712** [comment]
Thank you Fabian

**Comment by qwert4712** [comment]
FYI 
the problem was not IP V6

There is a option ""Aktive WLAN-Geräte dürfen untereinander kommunizieren" on the Fritzbox.
This was enabled on the Repeater but disabled on the Main Fritzbox.

When setting up the script the Gerbo seems to be conneted to the Repeater - because it work for about 6h.
Then the connection failed.
The Gerbo was then connected always to the Main Fritzbox and a ping of the Shelly failed.

The AVM Support needs only 1 Minute to give the right hint.
